### ISSUE TITLE
Tags within () are ignored.

### ISSUE THREAD

**Issue by VikasRana** [Chr1st-oo/pydeezer#1]
Wonderful program.

But i see tracks being downloaded as Message To My Future Ex.mp3 instead of lke what it says on the Deezloader page to album Message To My Future Ex (Radio Edit).mp3

Do you think its happening while tagging the audios?

**Comment by acgonzales** [comment]
Sorry, I accidentally edited your post. Getting a hard time using the official GitHub mobile app.

Yes, I think the problem is in the tagging method. I completely forgot about those () tags to include in the title. I will work on it once I have my hands on a computer.

**Comment by acgonzales** [comment]
I think that fixes the issue. Thanks for using my package :)
