### ISSUE TITLE
GUI for this

### ISSUE THREAD

**Issue by delrius-euphoria** [Chr1st-oo/pydeezer#12]
I was working on a GUI for music player and wanted to obtain tags for music and came across this, so I found out GUI is inside your todo list, so maybe I could help, with tkinter GUI. Well to know more about the GUI I make, just visit my github repo and also anyway to pinpoint tracks? Using the `search_track` it finds inaccurate tracks. Any ideas to point on exact song on searches like 'Justin Bieber & benny blanco - Lonely'. Thanks :D

**Comment by acgonzales** [comment]
Hi, thanks for taking interest on contributing to this repo. 

> Using the search_track it finds inaccurate tracks.

I see when you search using that query: `Justin Bieber & benny blanco - Lonely`, it gives the piano version as the first result. That is intended, if you search the same query on the official Deezer it will give similar results. The way I see it, to have an accurate result, you should input "less" specific keywords. If I want to search Justin Bieber's Lonely featuring Benny Blanco, I'll search for `lonely - justin bieber`.

> Any ideas to point on exact song on searches

If you really want to have an EXACT match. The only idea I can think of is to get the track's id from Deezer and get the track using the `get_track(track_id)` method.

**Comment by delrius-euphoria** [comment]
Is there a way to get track id, from deezers site? or something?

**Comment by acgonzales** [comment]
Yes, definitely. All the tracks and search results shown in Deezer is an anchor tag and you can take its `id` in its `href`.

Lonely - Justin Bieber, Benny Blanco have this link: `https://www.deezer.com/en/track/1110767312`. The last part is actually the track's id so `1110767312`.

**Comment by nihaalnz** [comment]
Sorry for continuing this issue, but how do you get the link, the website seems to have a share link for the song and that is `https://deezer.page.link/xrYh93mFnT3xYvZt7`.

**Comment by nihaalnz** [comment]
Im sorry for continuing this issue, but how do you get the link, the link that can be shared from deezer is `https://deezer.page.link/xrYh93mFnT3xYvZt7`.
