### ISSUE TITLE
Get download progress

### ISSUE THREAD

**Issue by delrius-euphoria** [Chr1st-oo/pydeezer#13]
Is there any way to retrieve the downloaded chunk and total chunk size? To use for a tkinter progressbar.

**Comment by acgonzales** [comment]
You should extend the [BaseProgressHandler](https://github.com/Chr1st-oo/pydeezer/blob/e9a12802c5ecc33a634060f95daf4eb1f93f2931/pydeezer/ProgressHandler.py#L11) and override the `initialize`, `update` and `close` method according to your liking.

Here are some sample classes extending the `BaseProgressHandler`:

- [DefaultProgressHandler](https://github.com/Chr1st-oo/pydeezer/blob/e9a12802c5ecc33a634060f95daf4eb1f93f2931/pydeezer/ProgressHandler.py#L33)
- Downloader's [ProgresHandler](https://github.com/Chr1st-oo/pydeezer/blob/e9a12802c5ecc33a634060f95daf4eb1f93f2931/pydeezer/Downloader.py#L19)
- Sample [ProgressHandler](https://github.com/Chr1st-oo/pydeezer#code) in README.md

**Comment by delrius-euphoria** [comment]
It seems with the GUI its quite not possible or so. But its fine, I will use the CLI for this purpose, the progressbar looks beautiful.
