### ISSUE TITLE
can't encode character while saving song lyrics 

### ISSUE THREAD

**Issue by isoldmysoull** [Chr1st-oo/pydeezer#3]
i got this error while downloading a song: 
UnicodeEncodeError: 'charmap' codec can't encode character '\u2005' in position 29: character maps to <undefined>

i fixed by add encoding to save lyrics in save lyrics function:
with open(save_path, "w") as f --> with open(save_path, "w", encoding="utf-8") as f

**Comment by acgonzales** [comment]
Thanks, you can submit a pull request if you like.
