### ISSUE TITLE
MP3_320 not working. Says too many data to unpack.

### ISSUE THREAD

**Issue by VikasRana** [Chr1st-oo/pydeezer#5]
`track["download"](download_dir, filename = 'Track 01.mp3', quality=track_formats.MP3_320)` 

isnt working. 

Raises this error
`File "C:\Python37\lib\site-packages\pydeezer\Deezer.py", line 404, in download_track
    track, quality, fallback=fallback, renew=renew, **kwargs)`

`ValueError: too many values to unpack (expected 2)`

**Comment by acgonzales** [comment]
I am in no way of testing the code now so I edited the code directly here at GitHub and I think it should be working properly now.

You may reopen this if the issue still persists.

**Comment by VikasRana** [comment]
Works again. Awesome project.
