### ISSUE TITLE
Login / family account

### ISSUE THREAD

**Issue by JOJ0** [Chr1st-oo/pydeezer#7]
Hi, not an issue but a question and being too lazy to really read through your code. 

Does this module support logging in to deezer with an email address and does it also support then switching to a „subprofile“ of a deezer family account? Thus making downloading of this subaccounts playlists possible.

thanks in advance!
jojo

**Comment by JOJ0** [comment]
hi again, just read your readme.md a little  closer and found out that login is realized using the arl token found in cookies. so thequestion which remains is  now only the support of family subaccounts. it could be easily answered by checkin the arl string in cookies and switching back an forth between subaccounts, seeing if it changes. i cant check it myself right now because i dont have a computer until next week. if you know by heart please tell me, if not i will try this when i am back home.
thanks for this python library in any case sounds promising! 
all the best.
jojo

**Comment by acgonzales** [comment]
> Does this module support logging in to deezer with an email address

Not right now, no. Right now the only way of logging in is through the ARL cookie. I have some ideas on how to support logging in with email address but I don't really have the time right now and its currently not my priority in this module.

> Does it also support then switching to a „subprofile“ of a deezer family account? 

I'm sorry but I haven't had the resources to check how it works on Deezer family accounts. But if Deezer treats those subaccounts like a regular account, they should provide unique ARLs for each subaccount.

> Thus making downloading of this subaccounts playlists possible.

If the playlist is not private, it can be easily searched and downloaded using this module even if you an account that is not the owner of the playlist.

Hope this answers your concern.

Thank you for showing interest in this module.

**Comment by JOJ0** [comment]
> Not right now, no. Right now the only way of logging in is through the ARL cookie. I have some ideas on how to support logging in with email address but I don't really have the time right now and its currently not my priority in this module.

for me personally arl would be sufficient.
> 
> 

> I'm sorry but I haven't had the resources to check how it works on Deezer family accounts. But if Deezer treats those subaccounts like a regular account, they should provide unique ARLs for each subaccount.

it seems to be different but i am not sure and will check. workflow is logging in with the one email address that is shared with the whole family account members. then in deezer interface you have to switch to your account. similar to netflix btw.

 some tools like deezloader remix dont support family accounts. you put in the family mail address but then dont have the option to switch to your particular subaccount. the deezloader interface just does not have that and you stay within the account that registered the family account. 

for comparision in spotify each family member logs in with his/her own email address.


> 
> If the playlist is not private, it can be easily searched and downloaded using this module even if you an account that is not the owner of the playlist.

this  could be a workaround even if arl and subaccounts dont work :-)

> Hope this answers your concern.

yes will test some and report back.

> Thank you for showing interest in this module.

thanks a lot for your quick reply. appreciated!

**Comment by JOJ0** [comment]
Hi I switched to spotify and dont have a deezer family account anymore, so dont currently have the resources to test this. my apologies, i think you can close this issue/question.
